# Generated by Django 3.0.5 on 2021-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0002_stockprice_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='hour',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='sector',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
