# Generated by Django 3.0.5 on 2022-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0003_auto_20210330_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
