# Generated by Django 3.0.5 on 2020-10-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(help_text='Usabo para setor, subsetor e segmento', max_length=150)),
                ('pai', models.ForeignKey(help_text='Montar a hierarquia de setor, subsetor, segmento', on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.Setorial')),
            ],
        ),
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_1', models.CharField(blank=True, help_text='Usado em algumas tabelas da B3 que relacionam os papeis por esta chave.', max_length=100, null=True)),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('setorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.Setorial')),
            ],
        ),
    ]
