# Generated by Django 3.0.5 on 2020-10-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorial',
            name='pai',
            field=models.ForeignKey(help_text='Montar a hierarquia de setor, subsetor, segmento', null=True, on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.Setorial'),
        ),
    ]
