# Generated by Django 3.0.5 on 2020-11-23 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_reference_data', '0003_auto_20201012_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('b3_brokering', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('b3_settlement', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('b3_registration', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerBrokerageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('order', 'Order')], default='order', max_length=12)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('stock_brokering', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stock_total', models.DecimalField(blank=True, decimal_places=2, help_text='Brokerage + ISS', max_digits=6, null=True)),
                ('stock_day_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock_day_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stock_day_trade_total', models.DecimalField(blank=True, decimal_places=2, help_text='Brokerage + ISS', max_digits=6, null=True)),
                ('options_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('options_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('options_trade_total', models.DecimalField(blank=True, decimal_places=2, help_text='Brokerage + ISS', max_digits=6, null=True)),
                ('bbt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.BrokerBrokerageType')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3_reference_data.Broker')),
            ],
        ),
    ]
