# Generated by Django 3.0.5 on 2020-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_reference_data', '0004_b3taxes_broker_brokerbrokeragetype_brokertaxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b3taxes',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b3taxes',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokertaxes',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokertaxes',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
