# Generated by Django 3.0.5 on 2020-11-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_reference_data', '0005_auto_20201123_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokertaxes',
            name='bbt',
        ),
        migrations.RemoveField(
            model_name='brokertaxes',
            name='options_trade_total',
        ),
        migrations.RemoveField(
            model_name='brokertaxes',
            name='stock_day_trade_total',
        ),
        migrations.RemoveField(
            model_name='brokertaxes',
            name='stock_total',
        ),
        migrations.AddField(
            model_name='brokertaxes',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('order', 'Order')], default='order', max_length=12),
        ),
        migrations.AlterField(
            model_name='b3taxes',
            name='b3_brokering',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='b3taxes',
            name='b3_registration',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='b3taxes',
            name='b3_settlement',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='BrokerBrokerageType',
        ),
    ]
