# Generated by Django 3.0.5 on 2020-11-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_reference_data', '0006_auto_20201123_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
