# Generated by Django 3.0.5 on 2021-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmalert',
            name='timeframe',
            field=models.CharField(choices=[('15min', '15min'), ('1H', '1H'), ('2H', '2H'), ('4H', '4H'), ('D', 'D'), ('W', 'W')], default='15min', max_length=7),
        ),
    ]
