# Generated by Django 3.0.5 on 2021-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210601_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(blank=True, max_length=12, null=True)),
                ('alert', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
