# Generated by Django 3.0.5 on 2020-11-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('desdobramento', 'desdobramento'), ('bonificacao', 'bonificacao'), ('conversao', 'conversao')], max_length=24)),
                ('data_ex', models.DateField(blank=True, null=True)),
                ('data_new', models.DateField(blank=True, null=True)),
                ('group_valid', models.SmallIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=1, null=True)),
                ('qtt_operation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_code_change', models.CharField(blank=True, max_length=12, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.Ativos')),
            ],
        ),
    ]
