# Generated by Django 3.0.5 on 2020-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateevent',
            old_name='stock',
            new_name='asset',
        ),
        migrations.RemoveField(
            model_name='corporateevent',
            name='stock_code_change',
        ),
        migrations.AddField(
            model_name='corporateevent',
            name='asset_code_new',
            field=models.CharField(blank=True, help_text='For conversao only', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='corporateevent',
            name='asset_code_old',
            field=models.CharField(blank=True, help_text='For conversao only', max_length=12, null=True),
        ),
    ]
