# Generated by Django 3.0.5 on 2020-11-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_events', '0002_auto_20201125_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateevent',
            old_name='data_ex',
            new_name='date_ex',
        ),
        migrations.RenameField(
            model_name='corporateevent',
            old_name='data_new',
            new_name='date_new',
        ),
    ]
