# Generated by Django 3.0.5 on 2020-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20200517_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_key',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
