# Generated by Django 3.0.5 on 2020-11-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B3Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('b3_brokering', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True)),
                ('b3_settlement', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True)),
                ('b3_registration', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(help_text='Usabo para setor, subsetor e segmento', max_length=150)),
                ('pai', models.ForeignKey(help_text='Montar a hierarquia de setor, subsetor, segmento', null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_data.Setorial')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('order', 'Order')], default='order', max_length=12)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('stock_brokering', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stock_day_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock_day_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('options_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('options_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_1', models.CharField(blank=True, help_text='Usado em algumas tabelas da B3 que relacionam os papeis por esta chave.', max_length=100, null=True)),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('btc', models.DecimalField(blank=True, decimal_places=2, help_text='Soma btc de preferenciais e ordinarias', max_digits=15, null=True)),
                ('termo', models.DecimalField(blank=True, decimal_places=2, help_text='Soma termo de preferenciais e ordinarias', max_digits=15, null=True)),
                ('setorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.Setorial')),
            ],
        ),
    ]
