# Generated by Django 3.0.5 on 2020-10-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_auto_20201011_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='btc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soma btc de preferenciais e ordinarias', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='termo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soma termo de preferenciais e ordinarias', max_digits=15, null=True),
        ),
    ]
