# Generated by Django 3.0.5 on 2021-01-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_auto_20201207_0230'),
        ('reference_data', '0003_auto_20201012_0121'),
    ]

    operations = [
    ]
