# Generated by Django 3.0.5 on 2021-01-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0004_merge_20210115_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='b3taxes',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
