# Generated by Django 3.0.5 on 2021-01-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0005_b3taxes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b3taxes',
            name='title',
        ),
        migrations.AddField(
            model_name='b3taxes',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Trade'), ('daytrade', 'Day Trade')], default='regular', max_length=12),
        ),
    ]
