# Generated by Django 3.0.5 on 2021-05-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0006_auto_20210115_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(blank=True, max_length=12, null=True)),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
