# Generated by Django 3.0.5 on 2021-05-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0008_auto_20210524_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacoes',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
