# Generated by Django 3.0.5 on 2021-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='De')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Até')),
                ('stock_brokering', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tx de corretage - à vista')),
                ('stock_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ISS - à vista')),
                ('stock_day_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tx de corretage - Daytrade')),
                ('stock_day_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ISS - Daytrade')),
                ('options_trade_brokerage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tx de corretage - Opções')),
                ('options_trade_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ISS - Opções')),
            ],
        ),
    ]
